### ISSUE TITLE
No module named 'quart.flask_patch'

### ISSUE THREAD

**Issue by oschettler** [ntoll/textsmith#1]
I have tried the sequence 

* Installed redis: `apt install redis-server`
* Create and activate a virtual env, installed the requirements with `pip install -r requirements.txt`
* Launch the server: `make run`

Up until `make run`, everything works without errors. Then: 

````
hypercorn textsmith.app:app	
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/olav/Dokumente/textsmith/env/lib/python3.10/site-packages/hypercorn/asyncio/run.py", line 186, in asyncio_worker
    app = load_application(config.application_path, config.wsgi_max_body_size)
  File "/home/olav/Dokumente/textsmith/env/lib/python3.10/site-packages/hypercorn/utils.py", line 110, in load_application
    module = import_module(import_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/olav/Dokumente/textsmith/textsmith/app.py", line 23, in <module>
    import quart.flask_patch  # type: ignore # noqa
ModuleNotFoundError: No module named 'quart.flask_patch'
````

**Comment by oschettler** [comment]
To proceed, I've tried to `pip install quart.flask_patch`, which works ("Successfully installed quart.flask_patch-0.3.0"), but `make run` still complains about "No module named 'quart.flask_patch".

Next, I have commented out the [import of quart.flask_path](https://github.com/ntoll/textsmith/blob/main/textsmith/app.py#L23) and tried `make run`again. This time, the program crashes with 'No module named 'wtforms.fields.html5''. 

Oh well, it seems more porting is required to make textsmith run in 2024.
